### ISSUE TITLE
R 0.1 - upload OVA file to S3

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/s-k8-releases#16]
Upload OVA - S3 is a good option (in an bucket that allows public read access)

**Comment by GINAGC** [comment]
OVA from R 0.1 is here, please upload it to azure https://hcompl-my.sharepoint.com/:u:/g/personal/mariusz_ferdyn_h_com_pl/EaOCuPCAb9VGjL-Fk2KWK6sBvg1j5V0g-eiwOyNVXfisRA?e=oxl4zu

**Comment by IslamHeggy** [comment]
Created a bucket named glasswall-proxy-ova for the ova releases in Ohio and pushed the first ova there.
