### ISSUE TITLE
 List of components that are used in K8 project

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/s-k8-releases#29]
1) list of components that are used in K8 projects.

**Comment by mahnouman** [comment]
Those two are the major components, will keep thinking of the others as well:
Squid Cache , GNU GPL, http://www.squid-cache.org/
NGINX , 2-clause BSD , https://www.nginx.com/

**Comment by anejaalekh** [comment]
Used :-
kubectl 
helm 
istio 
knative

**Comment by GINAGC** [comment]
Information added here: https://github.com/k8-proxy/p-k8-licensing-compliance/blob/master/Components.md
