### ISSUE TITLE
IP related issue in Kubernetes cluster

### ISSUE THREAD

**Issue by susilupwork** [k8-proxy/s-k8-releases#51]
OVA/ AMI gets created with K8 cluster. 

We need to set a specific IP for the k8s node, So every time the node starts with the same IP so the node can work successfully. This is done manually right now. 

Solution required

**Comment by IslamHeggy** [comment]
I think another solution might be trying to figure out if k8s can accept re configuring the IP address everytime.

So we can automate the procedure every time the IP changes

**Comment by IslamHeggy** [comment]
After doing some research and testing rancher installation we haven't faced this problem. 

So this is not a a valid issue anymore after using Rancher.
