### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-releases#9]
**Configurable reverse proxy docker after OVA is built**
Being able to pass on the reverse proxy configuration parameters, like the target website(s), base domain, Cert, etc... after the OVA is built, can be via scripts or similar.

**Comment by NourEddineX** [comment]
@mahnouman Can you please provide more details about requirements?

**Comment by NourEddineX** [comment]
25552e6e3e1069d8fd49b4f560af9ed5ea2aaf2a
